# Generated by Django 3.1.1 on 2021-01-26 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorten_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='UrlData',
        ),
    ]
