# Generated by Django 3.1.1 on 2021-01-26 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorten_app', '0002_auto_20210126_2231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='url',
            new_name='original_url',
        ),
        migrations.AddField(
            model_name='url',
            name='shorten',
            field=models.CharField(default='w8dj03lsj', max_length=100),
        ),
    ]
